# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: true
warnings_are_errors: false

before_install:
  - sudo apt-get install -y libhdf5-dev=1.8.12
