# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
warnings_are_errors: false

# Following
# https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
cache:
  - ccache

addons:
  apt:
    packages:
     - ccache

# Following
# https://gist.github.com/episodeyang/dfa69365203639fcde5f2aae73f7d9ac
# https://docs.travis-ci.com/user/installing-dependencies/#installing-projects-from-source
# - wget https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/src/hdf5-1.10.0-patch1.tar.gz
#  - tar -xzf hdf5-1.10.0-patch1.tar.gz
#  - pushd hdf5-1.10.0-patch1 && ./configure --prefix=/usr --enable-cxx --enable-build-mode=production && sudo make install && popd
before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars

# This should only apply to Travis, since we'll never need the Read10X
# function, try this workaround, following
# https://github.com/satijalab/seurat/issues/1114#issuecomment-488092170
r_github_packages:
  - UCSF-TI/fake-hdf5r

# Notes:
# We can specify a specific version of an R package (older than the CRAN version)#
# https://github.com/r-lib/devtools/blob/master/vignettes/dependencies.Rmd#L20
